name: swipify
description: "The Digital Curator Platform - A swipe-to-clean privacy-first app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.3.1
  
  # UI & Theming
  google_fonts: ^8.0.2
  material_symbols_icons: ^4.2.0
  
  # Navigation
  go_router: ^17.1.0

  # Native Integrations for MVP
  
  # Swipe physics (will implement custom, but keeping hook here if needed package like appinio_swiper)
  flutter_card_swiper: ^7.0.0
  
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.5.5
  video_player: ^2.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
